getModel() can throw custom Error instead of return undefined
eclipse-cdt-cloud/tsp-typescript-client pull request #39
Opened 2021-10-17 19:31 UTC by haoadoresorange

Signed-off-by: Quoc-Hao Tran <quoc-hao.tran@polymtl.ca>

2021-10-17 19:33 UTC, haoadoresorange commented
I just find myself rewriting a lot of Error handler for this use case when getting the response model, so this is a suggestion, I'm not sure if it's the appropriate solution.

2021-10-17 22:38 UTC, paul-marechal reviewed
I understand the feeling, but I'm not sure if this is a very common usage scenario for this API... But maybe I'm wrong, I'd like to hear more feedback.

In the meantime, nothing prevents you from implementing those utility functions in your own project for reuse.

2021-10-17 22:38 UTC, paul-marechal commented on tsp-typescript-client/src/protocol/tsp-client-response.ts
> +    public tryGetModel(CustomError: new (msg: string, code?: number) => Error): never | T {
`never` actually is the empty type. Here the return type is strictly equivalent to just `T`.

2021-10-18 04:29 UTC, haoadoresorange commented on tsp-typescript-client/src/protocol/tsp-client-response.ts
> +    public tryGetModel(CustomError: new (msg: string, code?: number) => Error): never | T {
Yes that's true ! I Sorry I was just quickly adding it as an example, not actually using it. Thanks for spotting it out.

2021-11-05 14:39 UTC, haoadoresorange commented
Hi, sorry for the late reply !

> Is this change for being able to re-use a common error handler implementation? Please let me know what the advantages are

Yes, or just pass a custom error. It was just a short way for me to write the code, so instead of 
```typescript
const response = tsp.fetchExperiments();
try{
   if (! response.isOk()) throw new CustomError(response.statusMessage, response.statusCode)
   if (! response.getModel()) throw new CustomError(response.statusMessage)
} catch (e) {
   handleError(e)
}
```
Now I write
```typescript
   response.tryGetModel(handleError)
```
Idk about how the `isOk` and `getModel` are usually used, but I find myself just couple them together most of the time. Are you familiar with the matter ?

2021-11-06 21:33 UTC, haoadoresorange commented
should I squash all the commits ?

2021-11-22 16:22 UTC, bhufmann approved these changes
I'm ok with this new API. Thanks!

2022-06-06 21:10 UTC, marco-miller commented
@bhufmann -Bernd, how should we handle this failing legal check you think?

2022-06-16 12:59 UTC, bhufmann commented
> @bhufmann -Bernd, how should we handle this failing legal check you think?

So that @haoadoreorange can contribute this project, he has to sign the ECA as described in the [contribution guide: ](https://github.com/eclipse-cdt-cloud/tsp-typescript-client/blob/master/CONTRIBUTING.md) and then update the patch (e.g. rebase).

2023-01-25 14:10 UTC, marco-miller requested changes
-As per the previous comments thread (feedback to/for the author; thanks again).

2023-10-18 13:08 UTC, bhufmann commented
Closing this PR since it hasn't be active for a while. Please reopen if required.

2023-10-18 13:08 UTC, closed without merging