Add ConnectionStatusListener to RestClient
eclipse-cdt-cloud/tsp-typescript-client pull request #49
Opened 2022-02-22 16:05 UTC by PatrickTasse

Clients can add a connection status listener to the RestClient to be
notified when the connection goes up or down. The connection status is
detected based on whether any HTTP request can be completed or not.

When a listener is added it will immediately receive the current status
through the listener interface.

Change-Id: I5f7fcbf4b94380b2ea349755a400bd61bbadc7d2
Signed-off-by: Patrick Tasse <patrick.tasse@ericsson.com>

2022-03-09 22:23 UTC, hriday-panchasara commented
LGTM. Works well with the suggested implementation in https://github.com/theia-ide/theia-trace-extension/pull/671

2022-03-16 14:41 UTC, bhufmann requested changes

2022-03-16 14:41 UTC, bhufmann commented on tsp-typescript-client/src/protocol/rest-client.ts
> +            const status = response.status <= 500;
500 or 501 can be returned by the server, so the status should be true. You will need to be more selective when deciding that the server is down.

2022-03-16 19:24 UTC, PatrickTasse commented on tsp-typescript-client/src/protocol/rest-client.ts
> +            const status = response.status <= 500;
I looked at the status code and how we use them, and I would guess that it should be only 500 and 501 that map to true, and the others >= 502 map to false. Would that be OK?

2022-03-18 15:25 UTC, bhufmann requested changes

2022-03-18 15:25 UTC, bhufmann commented on tsp-typescript-client/src/protocol/rest-client.ts
> +
You should document what it means if connection listener is called with false or true. Probably in the ConnectionStatusListener doc

2022-03-23 15:42 UTC, merged