Add contribution documentation
eclipse-cdt-cloud/tsp-typescript-client pull request #59
Opened 2022-04-05 19:30 UTC by hoangphamEclipse

This commit adds CONTRIBUTING.md to inform contributors of important contribution policies, legal documents, agreements and guidelines.

2022-04-06 17:16 UTC, bhufmann requested changes
The added file looks good. I think we should have sentence in the toplevel README.md with link to the CONTRIBUING.md file. Could you please add that?

2022-04-06 18:07 UTC, hoangphamEclipse commented
Sure I will do that

2022-04-07 17:10 UTC, bhufmann approved these changes
Looks good to me. Thanks for providing this.

2022-04-07 20:26 UTC, Rodrigoplp-work approved these changes

2022-04-07 20:58 UTC, merged