Add metadata to timegraph deserializer
eclipse-cdt-cloud/tsp-typescript-client pull request #63
Opened 2022-06-06 17:47 UTC by bhufmann

This PR adds support for metadata in the timegraph deserializer. It includes also unit tests to verify this change.

Signed-off-by: Rodrigo Pinto <rodrigo.pinto@calian.ca>
Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>

2022-06-06 17:49 UTC, bhufmann commented
This PR is based on PR #62. It includes a modified version of #62 plus unit tests.

2022-06-07 16:38 UTC, marco-miller requested changes

2022-06-07 16:38 UTC, marco-miller commented on tsp-typescript-client/src/models/entry.ts
> +    metadata: undefined
The style of this file would expect a trailing comma even here too.

2022-06-07 16:38 UTC, marco-miller commented on tsp-typescript-client/src/protocol/tsp-client.test.ts
> +      const tids = metadata?.pid;
.tids, it seems.

2022-06-07 16:38 UTC, marco-miller commented on tsp-typescript-client/src/protocol/tsp-client.test.ts
> +      const pids = metadata?.pid;
.pids, rather?

2022-06-07 16:38 UTC, marco-miller commented on tsp-typescript-client/src/protocol/tsp-client.test.ts
> +      const exec = metadata?.pid;
.exec instead?

2022-06-07 16:38 UTC, marco-miller commented on tsp-typescript-client/src/protocol/tsp-client.test.ts
> +      expect(pids).toBeDefined();
If using .pids instead above, this check fails as that gets undefined.

Maybe passing this somehow will lead to failing more checks below, if more get undefined, or if any actual length isn't 1.

2022-06-10 12:13 UTC, bhufmann commented on tsp-typescript-client/src/models/timegraph.ts
> +    metadata: undefined
Done

2022-06-10 12:27 UTC, bhufmann commented on tsp-typescript-client/src/protocol/tsp-client.test.ts
> +      const tids = metadata?.pid;
copy-paste error... I'll fix it

2022-06-10 12:29 UTC, bhufmann commented on tsp-typescript-client/src/protocol/tsp-client.test.ts
> +      const pids = metadata?.pid;
Done

2022-06-10 12:29 UTC, bhufmann commented on tsp-typescript-client/src/protocol/tsp-client.test.ts
> +      const exec = metadata?.pid;
Done

2022-06-10 12:33 UTC, bhufmann commented on tsp-typescript-client/src/protocol/tsp-client.test.ts
> +      expect(pids).toBeDefined();
In the test file the key is define as `pid`.

2022-06-10 12:36 UTC, bhufmann commented on tsp-typescript-client/src/models/entry.ts
> +    metadata: undefined
Done

2022-06-10 14:42 UTC, marco-miller commented on tsp-typescript-client/src/models/timegraph.ts
> +    metadata: undefined
Pushed?

2022-06-10 14:47 UTC, marco-miller commented on tsp-typescript-client/src/protocol/tsp-client.test.ts
> +      const exec = metadata?.pid;
You changed it to `exec_name`, rather, which LGTM.

2022-06-13 17:50 UTC, marco-miller approved these changes

2022-06-14 14:24 UTC, merged