Make TspClient reuseable interface
eclipse-cdt-cloud/tsp-typescript-client pull request #83
Opened 2023-07-21 08:45 UTC by sgraband

The `TspClient` is now an interface that can be used for other implementations. The existing functionality was moved to the `DefaultTspClient`. This means adopters now need to initialize the `DefaultTspClient` type instead of `TspClient` to get the default behavior. However this makes the package more flexible as different implementations can be provided, e.g. a proxy client in a Theia frontend.

Part of https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/976

Contributed on behalf of STMicroelectronics

Note: Once this is merged i can update [this PR](https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/990) to consume the changes.

2023-07-21 13:55 UTC, colin-grant-work commented on tsp-typescript-client/src/protocol/default-tsp-client.ts
> +export class DefaultTspClient implements TspClient {
Perhaps a more descriptive name would be possible? What distinguishes this client from e.g. the proposed JSON RPC client is that it makes HTTP calls directly, so perhaps it should be `HttpTspClient` or something similar?

2023-07-24 06:53 UTC, sgraband commented on tsp-typescript-client/src/protocol/default-tsp-client.ts
> +export class DefaultTspClient implements TspClient {
Good Idea! I added a commit with the rename and also added an export for the `HttpTspClient` to the `index.ts`.

2023-07-28 16:09 UTC, marco-miller requested changes
Thanks for this enabling contribution yes. So these would be my few (minor) comments.

Now this PR would require extensions [1,2,3] adaptations, so they build and work upon using it. Would you be able to contribute companion PRs for those alongside this one, accordingly? The goal would also be to further test this very PR that way, making sure that it works in [1,2,3]'s own contexts in turn. The original goal of supporting [4] remains alongside.

The concern of potentially breaking other (unforeseen) client integrations remains, though. Even if likely only a matter of renaming the type; as this has been a published API for a while now. Is there something we could do for this, say, scaffolding a backward-compatible (yet lightweight) structure first? -Which would come with a deprecation plan or so.

[1] https://github.com/eclipse-cdt-cloud/theia-trace-extension
[2] https://github.com/eclipse-cdt-cloud/vscode-trace-extension
[3] https://github.com/eclipse-cdt-cloud/vscode-trace-server
[4] https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/990

2023-08-07 07:42 UTC, sgraband commented
@marco-miller I updated the PR according to your two feedback comments. I will also provide PRs in the coming days for the dependedent projects.

Regarding the breaking of other dependent projects: I think the main problem tha we have is that the new interface has the same name as the old constructor. Hence exporting a constructor for TspClient will not work if i am not mistaken. Do you have another idea on how to achieve this?

BTW, i feel like it makes sense to get this PR merge ready, before updating the PRs in the dependent projects in case we change something here.

2023-08-07 19:34 UTC, marco-miller commented
> @marco-miller I updated the PR according to your two feedback comments. I will also provide PRs in the coming days for the dependedent projects.

Thanks again for all this.

> Regarding the breaking of other dependent projects: I think the main problem tha we have is that the new interface has the same name as the old constructor. Hence exporting a constructor for TspClient will not work if i am not mistaken. Do you have another idea on how to achieve this?

We could consider keeping the legacy constructor (class) as is. While making it extend a new, differently named interface, behind the scenes -so to speak. Then add the new constructable sibling alongside that legacy one (extending that interface too). Existing clients wouldn't be broken, yet could eventually choose to switch to the new implementation.

> BTW, i feel like it makes sense to get this PR merge ready, before updating the PRs in the dependent projects in case we change something here.

Agree; makes sense to me too.

2023-08-08 09:11 UTC, sgraband commented
> We could consider keeping the legacy constructor (class) as is. While making it extend a new, differently named interface, behind the scenes -so to speak. Then add the new constructable sibling alongside that legacy one (extending that interface too). Existing clients wouldn't be broken, yet could eventually choose to switch to the new implementation.

Would we really provide a "separate implementation" for the old constructor? Wouldnt it be sufficient to do something like:

```ts
export class TspClient extends HttpTspClient {}
```

This way we do not need to provide another implementation or delegate and existings clients will not break. WDYT?

Do you have any suggestions for the name of the interface? Are we planning to rename it to TspClient once we deprecate the constructor or should the name be permanent?

2023-08-08 19:12 UTC, bhufmann commented
> > > > Do you have any suggestions for the name of the interface? Are we planning to rename it to TspClient once we deprecate the constructor or should the name be permanent?
> > > 
> > > 
> > > How about `TraceServerProtocol`?
> > 
> > 
> > If I may, I'd throw `TraceClient` for consideration because the way the interface is defined it's all methods to interface with some Trace Server and it seems rather protocol-agnostic?
> 
> Finding good names are often tricky. `TraceServerProtocol` feels a bit long and `TraceClient` doesn't have a clear meaning for me.
> 
> With this change `TspClient` is an interface. The name doesn't indicate that. In Java, I like the naming convention that interfaces start with `I`. But this is discouraged in the Typescript community. So, I'm ok with keeping `TspClient` for the interface. `HttpTspClient` then makes sense for the HTTP implementation.

 "TspClient" as interface name and "HttpTspClient implements TspClient" would make sense. For backwards-compatibility reasons  and to avoid having to update each user of TspClient (theia-trace-extension and vscode-trace-extension) right away we don't have a choice to find a new name for the interface. Maybe using the prefix I is not such a bad idea in this case. I have seen that being done in the actual VsCode Typscript code base. So we wouldn't be the only ones :-)

WDYT?

2023-08-08 19:42 UTC, marco-miller commented
Adding to @bhufmann's latest proposal (which I'd foster, along with @paul-marechal's `alias` one): the exact list of known client extensions not to break is `[1,2,3]` in [this previous reply](#pullrequestreview-1552320722). -Just a friendly reminder.

2023-08-09 10:16 UTC, paul-marechal commented on tsp-typescript-client/src/protocol/tsp-client.ts
> +export const ITspClient = Symbol("ITspClient");
Is it just me or this feels out of place in this repository?

I imagine that this is for use in Theia with Inversify?

Whatever Theia extension is requiring some `TspClient` abstraction should define it themselves IMO. It's not like we can do something like:

```ts
import { ITspClient, HttpTspClient } from 'tsp-typescript-client';
// ...
bind(ITspClient).to(HttpTspClient);
```

Since `HttpTspClient` isn't decorated with `@injectable()` inversify is most likely to complain. It also doesn't make a lot of sense to me to have such a binding?

I'd imagine a Theia extension doing something like:

```ts
import { interfaces } from 'inversify';
import { ITspClient, HttpTspClient } from 'tsp-typescript-client';
// ...
export const TspClientFactory = Symbol('TspClientFactory') as symbol & interfaces.Abstract<TspClientFactory>;
export type TspClientFactory = (tspUrl: string) => ITspClient;
// ...
bind(TspClientFactory).toFunction(tspUrl => new HttpTspClient(tspUrl));
```

Or maybe something like the following if you have the need for a shared singleton:

```ts
import { interfaces } from 'inversify';
import { ITspClient } from 'tsp-typescript-client';
// ...
export const TspClientSingleton = Symbol('TspClientSingleton') as symbol & interfaces.Abstract<TspClientSingleton>;
export type TspClientSingleton = ITspClient;
// ...
bind(TspClientSingleton)
    .toDynamicValue(ctx => {
        // ...
        return /* whatever implements TspClientSingleton */;
    })
    .inSingletonScope();
```

Or maybe you need some kind of async provider?

The gist is that Inversify service identifiers heavily depend on your extension's design.

2023-08-09 11:40 UTC, sgraband commented on tsp-typescript-client/src/protocol/tsp-client.ts
> +export const ITspClient = Symbol("ITspClient");
The use case in the `theia-trace-extension` would be this one:
```ts
import { interfaces } from 'inversify';
import { ITspClient } from 'tsp-typescript-client';
// ...
export const TspClientSingleton = Symbol('TspClientSingleton') as symbol & interfaces.Abstract<TspClientSingleton>;
export type TspClientSingleton = ITspClient;
// ...
bind(TspClientSingleton)
    .toDynamicValue(ctx => {
        // ...
        return /* whatever implements TspClientSingleton */;
    })
    .inSingletonScope();
```

I simply wanted to offer the Symbol for convenience and simply inject like this:
```ts
    bind(ITspClient)
        .toDynamicValue(ctx => {
            return ...
        })
        .inSingletonScope();
```

But i am also fine with removing this and doing this in the extension itself :+1:

2023-08-09 12:39 UTC, sgraband commented on tsp-typescript-client/src/protocol/tsp-client.ts
> +export const ITspClient = Symbol("ITspClient");
When i remove the Symbol from here and define a new one in the `theia-trace-extension` i run into a problem:

So basically i have a `frontend-module`:

```ts
// The new symbol
export const TspClientProxy = Symbol('TspClientProxy');
export type TspClientProxy = ITspClient;
// binding the proxy
bind(TspClientProxy)
    .toDynamicValue(ctx => {
        const connection = ctx.container.get(WebSocketConnectionProvider);
        return connection.createProxy<ITspClient>(TRACE_SERVER_CLIENT);
    })
   .inSingletonScope();
// binding the wrapper for the TspClientProxy
bind(TheiaRpcTspProxy).toSelf().inSingletonScope();
```

The `TheiaRpcTspProxy` looks like this:
```ts
@injectable()
export class TheiaRpcTspProxy implements ITspClient {
    public constructor(@inject(TspClientProxy) protected tspClient: ITspClient) {}
```

This results in this error:

> index.js:89 Error: @inject called with undefined this could mean that the class TheiaRpcTspProxy has a circular dependency problem. You can use a LazyServiceIdentifer to  overcome this limitation.

Beforehand, while using the `export const ITspClient = Symbol("ITspClient");` instead of `TspClientProxy` symbol it worked just fine. Do you know if i missed something or if this is an architectural flaw?

2023-08-09 13:11 UTC, sgraband commented on tsp-typescript-client/src/protocol/tsp-client.ts
> +export const ITspClient = Symbol("ITspClient");
Great that worked! Thanks! I updated the PR. I also quickly tested this with the `theia-trace-extension` on main and it does not cause any problems.

2023-08-09 13:42 UTC, paul-marechal commented on tsp-typescript-client/src/protocol/tsp-client.ts
> +export type TspClient = HttpTspClient;
Something I didn't notice before but exporting `TspClient` here creates a circular dependency between `tsp-client.ts` and `http-tsp-client.ts`. It is currently fine because `http-tsp-client` only imports an interface from `tsp-client`, but it's still kinda smelly.

I would argue that it's fine to remove it from this file and instead add the following to the `index.ts` file:

```ts
// TODO: remove this deprecated alias?
export { /** @deprecated */ HttpTspClient as TspClient  } from './protocol/http-tsp-client';
```

2023-08-09 13:44 UTC, paul-marechal commented on tsp-typescript-client/src/protocol/tsp-client.ts
> +export type TspClient = HttpTspClient;
Ok ignore that as moving the symbol out of this file would break the following use site:

https://github.com/eclipse-cdt-cloud/theia-trace-extension/blob/7e50501e5bada64c8ba506d00f71a4268546573a/packages/base/src/trace-manager.ts#L2

2023-08-09 19:03 UTC, marco-miller requested changes
Thanks again for the rework. At this stage, most of the fix-up commits could be squashed, as they're review-based steps more than commitable increments. The resulting commit message(s) can be confirmed alongside.

2023-08-10 06:58 UTC, sgraband commented on tsp-typescript-client/src/protocol/tsp-client.ts
> +export type TspClient = HttpTspClient;
The const export does not allow `TspClient` to be used as a type in the consumed code, therefore we also need the type. The deprecation notice is duplicated so that it is displayed on the type as well as the constructors.

I will add a comment and squash the commits.

2023-08-10 08:32 UTC, paul-marechal commented on tsp-typescript-client/src/protocol/tsp-client.ts
> +export type TspClient = HttpTspClient;
While we do need to export the `TspClient` symbol as a value and as a type, the deprecation notice applied to one should be applied to the other as well (from my experience with the Theia codebase) so we don't need the duplicated comment.

Alternatively, the following notation would also work (and expose `TspClient` as a value and a type):

```ts
export { /** @deprecated */ HttpTspClient as TspClient } from './http-tsp-client';
```

I don't have any preference, just sharing my experience. Do as you see fit!

2023-08-10 09:16 UTC, sgraband commented on tsp-typescript-client/src/protocol/tsp-client.ts
> +export type TspClient = HttpTspClient;
When the deprecation notice is duplicated it will show the same notice twice on the import, which is not really desirable imho. Adding the notice to only one of the two exports leads to weird behavior e.g. no strike-throughs and no notice on consturctors.

After some testing i would argue that the best results come with:
```ts
export { /** @deprecated */ HttpTspClient as TspClient } from './http-tsp-client';
```

This way it marks the constructors and imports as deprecated and strikes them through. When used as a type it is not shown as deprecated, but you still have the import that indicates it. But the user should probably change the types to `ITspClient` anyway and not to `HttpTspClient`, like the deprecation notice would indicate. So i think this is the best solution. Any objections or ideas?

2023-08-10 11:55 UTC, paul-marechal commented on tsp-typescript-client/src/protocol/tsp-client.ts
> +export type TspClient = HttpTspClient;
I guess the deprecation warning is not very important, and this alias is only useful until the various repositories that use it are updated. Sounds good enough?

2023-08-10 14:01 UTC, marco-miller approved these changes
Pending @bhufmann's 2nd review; thanks.
- I `yarn`-linked this client version into the aforementioned `[1,2,3]` and was able to build and run tests where available.
- I opened the files using `TspClient` and didn't notice new/related warnings in VSC.
- The `HttpTspClient` implementation looks identical to the legacy `TspClient` one to me locally.

2023-08-14 20:08 UTC, bhufmann approved these changes
It looks good to me. Works fine with `theia-trace-extension` and `vscode-trace-extension`.

Thanks for the contribution!

2023-08-14 20:39 UTC, MatthewKhouzam approved these changes
Nice modularity!

2023-08-14 20:41 UTC, merged